services:
  background:
    executable: ./background.exe
    custom:
      background:
        path: C:/Users/alexw/Documents/wallpaper.png
      shader:
        vert: C:/Users/alexw/repos/minimalist-shell/cmd/background/shader.vert
        frag: C:/Users/alexw/repos/minimalist-shell/cmd/background/shader.frag
      render:
        updaterate: 2000 # Update rate in milliseconds
        clearcolor: 423
        # clearcolor: "#701278"
  shell-event-publisher:
    executable: ./shell.exe
  windows-nats-driver:
    executable: ./driver.exe
    custom:
      launcher:
        includesystempath: true
        watchsystempath: true
        extensions: [ .exe, .lnk, .bat, .ps1, .url, .png, .jpg, .gif]
        sources:
          - path: C:/Users/alexw/Desktop
            recursive: true 
            watch: true
          - path: C:/Users/alexw/scripts
            recursive: true 
            watch: true
          - path: "C:/Users/alexw/AppData/Roaming/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
          - path: "C:/ProgramData/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
  hotkey-manager:
    executable: ./hotkeys.exe
    custom:
      keymap:
        - keys: ctrl+alt+r
          actions:
            - nats:
                subject: Shell.Restart
        - keys: ctrl+shift+p
          actions: 
            - nats: 
                subject: System.LaunchProgram
                payload: pwsh.exe
        - keys: ctrl+alt+shift+p
          actions: 
            - nats: 
                subject: System.LaunchProgramAsAdmin
                payload: pwsh.exe
