services:
  # The shell-app-runtime is a dependency of shell-event-publisher.
  # without it, shell events are only published when windows switch focus,
  # and the events don't contain as much information
  shell-app-runtime: 
    executable: C:\Windows\System32\ShellAppRuntime.exe
    autorestart: false
  shell-event-publisher:
    autorestart: false
    executable: ./bin/shell-event-publisher.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
  windows-nats-driver:
    executable: ./bin/windows-nats-driver.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
    autorestart: true
  nvim-server:
    executable: nvim.exe
    arguments:
      - --headless
      - --listen
      - 0.0.0.0:6666
    workingdirectory: C:/Users/alexw/repos
    autorestart: true
    forwardstdout: false
    forwardstderror: false
    forwardstdin: false
