services:
  toast:
    enabled: false
    executable: ./toast.exe
  background:
    enabled: false
    executable: ./background.exe
    background:
      path: C:/Users/alexw/Documents/wallpaper.png
    shader:
      vert: ../cmd/background/shader.vert
      frag: ../cmd/background/shader.frag
    render:
      updaterate: 2000 # Update rate in milliseconds
      clearcolor: f423
  events:
    executable: ./events.exe
    keyboardevents: false
    mouseevents: false
    shellevents: true
  driver:
    executable: ./driver.exe
    launcher:
      includesystempath: true
      watchsystempath: true
      extensions: [.exe, .lnk, .bat, .ps1, .url, .png, .jpg, .gif]
      sources:
        - path: C:/Users/alexw/Desktop
          recursive: true
          watch: true
        - path: C:/Users/alexw/scripts
          recursive: true
          watch: true
        - path: 'C:/Users/alexw/AppData/Roaming/Microsoft/Windows/Start Menu/'
          recursive: true
          watch: true
        - path: 'C:/ProgramData/Microsoft/Windows/Start Menu/'
          recursive: true
          watch: true
  hotkeys:
    executable: ./hotkeys.exe
    keymap:
      - keys: ctrl+win+s 
        actions:
          - nats:
              subject: System.LaunchProgram 
              payload: Steam.lnk
      - keys: ctrl+alt+r
        actions:
          - nats:
              subject: Shell.Restart
      - keys: pause 
        actions: 
          - nats:
              subject: Window.ToggleBorder 
  windowmanager:
    executable: ./windowmanager.exe
    layout: revolver
    actionkey: nullkey
    cyclekey: alt
    scalex: 0.99
    scaley: 0.98
    padding: 30
    smallscale: 0.5
    perimeter: 0.7
    animationframes: 100
    animationtime: 300
    barrels: 2
