services:
  background:
    autorestart: false
    executable: ./bin/background.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
    custom:
      background:
        path: C:/Users/alexw/Documents/wallpaper.png
      shader:
        vert: C:/Users/alexw/repos/minimalist-shell/cmd/background/vert.shader
        frag: C:/Users/alexw/repos/minimalist-shell/cmd/background/frag.shader
      render:
        updaterate: 2000 # Update rate in milliseconds
        clearcolor: 423
        # clearcolor: "#701278"
  shell-event-publisher:
    autorestart: false
    executable: ./bin/shell-event-publisher.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
  windows-nats-driver:
    custom:
      launcher:
        includesystempath: true
        watchsystempath: true
        extensions: [ .exe, .lnk, .bat, .ps1, .url, .png, .jpg, .gif]
        sources:
          - path: C:/Users/alexw/Desktop
            recursive: true 
            watch: true
          - path: C:/Users/alexw/scripts
            recursive: true 
            watch: true
          - path: "C:/Users/alexw/AppData/Roaming/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
          - path: "C:/ProgramData/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
    executable: ./bin/windows-nats-driver.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
    autorestart: true
  nvim-server:
    executable: nvim.exe
    arguments:
      - --headless
      - --listen
      - 0.0.0.0:6666
    workingdirectory: C:/Users/alexw/repos
    autorestart: true
    forwardstdout: false
    forwardstderror: false
    forwardstdin: false
  hotkey-manager:
    autorestart: false
    executable: ./bin/hotkey-manager.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
    custom:
      keymap:
        - keys: ctrl+alt+shift+b 
          actions: 
            - nats pub WindowControls.ShowBorder
        - keys: ctrl+alt+b 
          actions: 
            - nats pub WindowControls.HideBorder
        - keys: ctrl+win+left
          actions:
            - nats pub WindowControls.TileLeft
        - keys: ctrl+win+right
          actions:
            - nats pub WindowControls.TileRight
        - keys: ctrl+win+up
          actions:
            - nats pub WindowControls.Maximize
        - keys: ctrl+win+w 
          actions: 
            - nats pub WindowControls.Cycle

