services:
  # background:
  #   autorestart: false
  #   executable: ./bin/background.exe
  #   workingdirectory: C:/Users/alexw/repos/minimalist-shell
  shell-event-publisher:
    autorestart: false
    executable: ./bin/shell-event-publisher.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
  windows-nats-driver:
    custom:
      launcher:
        includesystempath: true
        watchsystempath: true
        extensions: [ .exe, .lnk, .bat, .ps1, .url, .png, .jpg, .gif]
        sources:
          - path: C:/Users/alexw/Desktop
            recursive: true 
            watch: true
          - path: C:/Users/alexw/scripts
            recursive: true 
            watch: true
          - path: "C:/Users/alexw/AppData/Roaming/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
          - path: "C:/ProgramData/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
    executable: ./bin/windows-nats-driver.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
    autorestart: true
  nvim-server:
    executable: nvim.exe
    arguments:
      - --headless
      - --listen
      - 0.0.0.0:6666
    workingdirectory: C:/Users/alexw/repos
    autorestart: true
    forwardstdout: false
    forwardstderror: false
    forwardstdin: false

