services:
  # The shell-app-runtime is a dependency of shell-event-publisher.
  # without it, shell events are only published when windows switch focus,
  # and the events don't contain as much information
  # This also enables the Windows menu, even when the SHELLPROC intercepts it.. investigate
  shell-app-runtime: 
    executable: C:\Windows\System32\ShellAppRuntime.exe
    autorestart: false
  # This one creates a bottom-most drawing context and renders 
  # an image. It would be cool if it had some custom shader support
  shell-background:
  shell-event-publisher:
    autorestart: false
    executable: ./bin/shell-event-publisher.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
  windows-nats-driver:
    custom:
      launcher:
        includesystempath: true
        watchsystempath: true
        sources:
          - path: C:/Users/alexw/Desktop
            recursive: true 
            watch: true
          - path: C:/Users/alexw/scripts
            recursive: true 
            watch: true
          - path: "C:/Users/alexw/AppData/Roaming/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
          - path: "C:/ProgramData/Microsoft/Windows/Start Menu/"
            recursive: true 
            watch: true
    executable: ./bin/windows-nats-driver.exe
    workingdirectory: C:/Users/alexw/repos/minimalist-shell
    autorestart: true
  nvim-server:
    executable: nvim.exe
    arguments:
      - --headless
      - --listen
      - 0.0.0.0:6666
    workingdirectory: C:/Users/alexw/repos
    autorestart: true
    forwardstdout: false
    forwardstderror: false
    forwardstdin: false
